# NUMPY - NUMerical PYthon
**Retail Sales Dataset**

In [1]:
#Install the libraries
!pip install numpy pandas matplotlib

Defaulting to user installation because normal site-packages is not writeable


In [2]:
#import the libraries
import numpy as np
import pandas as pd
import matplotlib as mp

print(np.__version__)

2.5.2


In [3]:
data = np.genfromtxt(
    "retail_orders.csv",
    delimiter=",",
    skip_header=1,
    dtype=None,
    encoding="utf-8"
)

print(data)
print("Shape:", data.shape)
print("Dimensions:", data.ndim)
print("Size:", data.size)
print("Data Type:", data.dtype)

[(101, 'Laptop', 'Electronics', 'Chennai', 2, 50000, 100000, 45000.)
 (102, 'Mobile', 'Electronics', 'Chennai', 3, 20000,  60000, 18000.)
 (103, 'Laptop', 'Electronics', 'Bangalore', 1, 50000,  50000, 45000.)
 (104, 'Mouse', 'Accessories', 'Chennai', 5,   500,   2500,   450.)
 (105, 'Mobile', 'Electronics', 'Bangalore', 2, 20000,  40000, 18000.)
 (106, 'Keyboard', 'Accessories', 'Chennai', 4,  1000,   4000,   900.)]
Shape: (6,)
Dimensions: 1
Size: 6
Data Type: [('f0', '<i8'), ('f1', '<U8'), ('f2', '<U11'), ('f3', '<U9'), ('f4', '<i8'), ('f5', '<i8'), ('f6', '<i8'), ('f7', '<f8')]


In [4]:
new_data = data.reshape(2, 3)

print(new_data)

[[(101, 'Laptop', 'Electronics', 'Chennai', 2, 50000, 100000, 45000.)
  (102, 'Mobile', 'Electronics', 'Chennai', 3, 20000,  60000, 18000.)
  (103, 'Laptop', 'Electronics', 'Bangalore', 1, 50000,  50000, 45000.)]
 [(104, 'Mouse', 'Accessories', 'Chennai', 5,   500,   2500,   450.)
  (105, 'Mobile', 'Electronics', 'Bangalore', 2, 20000,  40000, 18000.)
  (106, 'Keyboard', 'Accessories', 'Chennai', 4,  1000,   4000,   900.)]]


In [5]:
new_data = data.reshape(3,2)

print(new_data)

[[(101, 'Laptop', 'Electronics', 'Chennai', 2, 50000, 100000, 45000.)
  (102, 'Mobile', 'Electronics', 'Chennai', 3, 20000,  60000, 18000.)]
 [(103, 'Laptop', 'Electronics', 'Bangalore', 1, 50000,  50000, 45000.)
  (104, 'Mouse', 'Accessories', 'Chennai', 5,   500,   2500,   450.)]
 [(105, 'Mobile', 'Electronics', 'Bangalore', 2, 20000,  40000, 18000.)
  (106, 'Keyboard', 'Accessories', 'Chennai', 4,  1000,   4000,   900.)]]


In [6]:
new_data = data.reshape(6,1)

print(new_data)

[[(101, 'Laptop', 'Electronics', 'Chennai', 2, 50000, 100000, 45000.)]
 [(102, 'Mobile', 'Electronics', 'Chennai', 3, 20000,  60000, 18000.)]
 [(103, 'Laptop', 'Electronics', 'Bangalore', 1, 50000,  50000, 45000.)]
 [(104, 'Mouse', 'Accessories', 'Chennai', 5,   500,   2500,   450.)]
 [(105, 'Mobile', 'Electronics', 'Bangalore', 2, 20000,  40000, 18000.)]
 [(106, 'Keyboard', 'Accessories', 'Chennai', 4,  1000,   4000,   900.)]]


In [7]:
flat_data = data.flatten()

print(flat_data)

[(101, 'Laptop', 'Electronics', 'Chennai', 2, 50000, 100000, 45000.)
 (102, 'Mobile', 'Electronics', 'Chennai', 3, 20000,  60000, 18000.)
 (103, 'Laptop', 'Electronics', 'Bangalore', 1, 50000,  50000, 45000.)
 (104, 'Mouse', 'Accessories', 'Chennai', 5,   500,   2500,   450.)
 (105, 'Mobile', 'Electronics', 'Bangalore', 2, 20000,  40000, 18000.)
 (106, 'Keyboard', 'Accessories', 'Chennai', 4,  1000,   4000,   900.)]


In [8]:
ravel_data = data.ravel()

print(ravel_data)

[(101, 'Laptop', 'Electronics', 'Chennai', 2, 50000, 100000, 45000.)
 (102, 'Mobile', 'Electronics', 'Chennai', 3, 20000,  60000, 18000.)
 (103, 'Laptop', 'Electronics', 'Bangalore', 1, 50000,  50000, 45000.)
 (104, 'Mouse', 'Accessories', 'Chennai', 5,   500,   2500,   450.)
 (105, 'Mobile', 'Electronics', 'Bangalore', 2, 20000,  40000, 18000.)
 (106, 'Keyboard', 'Accessories', 'Chennai', 4,  1000,   4000,   900.)]


In [9]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [10]:
print(np.empty(5))

[1. 1. 1. 1. 1.]


In [11]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
print(np.arange(1,101,2))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [13]:
print(np.linspace(0, 100, 11))

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [14]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
print(np.full(5,100))

[100 100 100 100 100]


In [16]:
#Understanding Shape
sales = np.array([
    [5, 65000],
    [20, 800],
    [8, 4500],
    [15, 1500]
])
sales.shape

(4, 2)

In [17]:
sales.reshape(2, 4)

array([[    5, 65000,    20,   800],
       [    8,  4500,    15,  1500]])

In [18]:
sales.flatten()

array([    5, 65000,    20,   800,     8,  4500,    15,  1500])

In [19]:
sales.ravel()

array([    5, 65000,    20,   800,     8,  4500,    15,  1500])

In [20]:
#Flatten vs ravel
marks = np.array([
    [80, 75, 90],
    [65, 88, 92]
])

#if you want an independent copy
all_marks = marks.flatten().reshape(3,2)
print(all_marks)

#temporarily view all marks as one dimension:
all_marks = marks.ravel().reshape(3,2)
print(all_marks)

[[80 75]
 [90 65]
 [88 92]]
[[80 75]
 [90 65]
 [88 92]]


In [21]:
#Selecting data
print(sales)
print(sales[0])
print(sales[0, 1])
print(sales[:, 0])
print(sales[:, 1])

[[    5 65000]
 [   20   800]
 [    8  4500]
 [   15  1500]]
[    5 65000]
65000
[ 5 20  8 15]
[65000   800  4500  1500]


In [22]:
#Slicing data
print(sales[0:5])

[[    5 65000]
 [   20   800]
 [    8  4500]
 [   15  1500]]


In [23]:
print(sales[:, 1:3])

[[65000]
 [  800]
 [ 4500]
 [ 1500]]


In [24]:
#Reverse data
print(sales[::-1])

[[   15  1500]
 [    8  4500]
 [   20   800]
 [    5 65000]]


In [25]:
print(sales[::2])

[[    5 65000]
 [    8  4500]]


In [26]:
#Boolean filtering
units = np.array([5, 20, 8, 15, 30, 3])
units > 10

array([False,  True, False,  True,  True, False])

In [27]:
units[units > 10]

array([20, 15, 30])

In [28]:
high_sales = sales[sales[:, 0] > 10]
print(high_sales)

[[  20  800]
 [  15 1500]]


In [29]:
#Multiple Conditions
#AND
result = sales[
    (sales[:, 0] > 10) &
    (sales[:, 1] > 1000)
]
print(result)

[[  15 1500]]


In [30]:
#OR
result = sales[
    (sales[:, 0] > 10) |
    (sales[:, 1] > 1000)
]
print(result)

[[    5 65000]
 [   20   800]
 [    8  4500]
 [   15  1500]]


In [31]:
#NOT
sales[~(sales[:, 0] > 10)]

array([[    5, 65000],
       [    8,  4500]])

In [32]:
#Arithmetic Operations
quantity = np.array([5,10,3,8])
price = np.array([10,20,15,50])
print(quantity + price)
print(price - quantity)
sales = quantity * price
print(sales)
print(price / quantity)
print(quantity ** 2)

[15 30 18 58]
[ 5 10 12 42]
[ 50 200  45 400]
[2.   2.   5.   6.25]
[ 25 100   9  64]


In [33]:
#Broadcasting in Numpy
#Add a single number
price = np.array([100,200,300,400])
print(price + 50)

[150 250 350 450]


In [34]:
#Broadcasting using real example (Add GST)
price = np.array([1000,2000,3000,4000])
gst = 0.18
final_price = price + (price * gst)
print(final_price)

[1180. 2360. 3540. 4720.]


In [35]:
#Ecommerce Sales project
import numpy as np
import pandas as pd

#Create sales dataset
data = {"Product": ["Laptop","Phone","Headphones","Keyboard","Mouse","Monitor","Laptop","Phone","Headphones","Monitor","Keyboard","Mouse"],
        "Category": ["Electronics","Electronics","Accessories","Accessories","Accessories","Electronics","Electronics","Electronics","Accessories",
                     "Electronics","Accessories","Accessories"],
        "Quantity": [2, 5, 10, 8, 15, 3,1, 4, 12, 2, 6, 20],
        "Price": [55000, 30000, 2000, 1500,800, 25000, 55000, 30000,2000, 25000, 1500, 800],
        "Rating": [4.5, 4.2, 4.7, 4.1,4.6, 4.3, 4.8, 4.0,4.5, 4.4, 4.2, 4.7]
       }
df = pd.DataFrame(data)

print("\nOriginal Sales Data:")
print(df)


Original Sales Data:
       Product     Category  Quantity  Price  Rating
0       Laptop  Electronics         2  55000     4.5
1        Phone  Electronics         5  30000     4.2
2   Headphones  Accessories        10   2000     4.7
3     Keyboard  Accessories         8   1500     4.1
4        Mouse  Accessories        15    800     4.6
5      Monitor  Electronics         3  25000     4.3
6       Laptop  Electronics         1  55000     4.8
7        Phone  Electronics         4  30000     4.0
8   Headphones  Accessories        12   2000     4.5
9      Monitor  Electronics         2  25000     4.4
10    Keyboard  Accessories         6   1500     4.2
11       Mouse  Accessories        20    800     4.7


In [36]:
#Understanding the data
print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)


Shape:
(12, 5)

Columns:
Index(['Product', 'Category', 'Quantity', 'Price', 'Rating'], dtype='str')

Data Types:
Product         str
Category        str
Quantity      int64
Price         int64
Rating      float64
dtype: object


In [37]:
#Calculate Revenue by using numpy

df["Revenue"] = np.multiply(df["Quantity"],df["Price"])

print(df[["Product","Quantity","Price","Revenue"]])


       Product  Quantity  Price  Revenue
0       Laptop         2  55000   110000
1        Phone         5  30000   150000
2   Headphones        10   2000    20000
3     Keyboard         8   1500    12000
4        Mouse        15    800    12000
5      Monitor         3  25000    75000
6       Laptop         1  55000    55000
7        Phone         4  30000   120000
8   Headphones        12   2000    24000
9      Monitor         2  25000    50000
10    Keyboard         6   1500     9000
11       Mouse        20    800    16000


In [38]:
#Basic Numpy statistics
revenue = df["Revenue"].to_numpy()

print("Total Revenue:",np.sum(revenue))
print("Average Revenue:",np.mean(revenue))
print("Highest Revenue:",np.max(revenue))
print("Lowest Revenue:",np.min(revenue))
print("Revenue Standard Deviation:",np.std(revenue))

Total Revenue: 653000
Average Revenue: 54416.666666666664
Highest Revenue: 150000
Lowest Revenue: 9000
Revenue Standard Deviation: 46741.23506664705


In [39]:
#Find the highest revenue transaction
highest_index = np.argmax(revenue)
print(df.iloc[highest_index])

Product           Phone
Category    Electronics
Quantity              5
Price             30000
Rating              4.2
Revenue          150000
Name: 1, dtype: object


In [40]:
#Product wise sales
product_sales = df.groupby("Product")["Quantity"].sum()
print(product_sales)

Product
Headphones    22
Keyboard      14
Laptop         3
Monitor        5
Mouse         35
Phone          9
Name: Quantity, dtype: int64


In [41]:
# Find best-selling product
best_selling_product = product_sales.idxmax()
best_selling_quantity = product_sales.max()
print("\nBest Selling Product:",best_selling_product)
print("Units Sold:",best_selling_quantity)


Best Selling Product: Mouse
Units Sold: 35


In [42]:
#Product wise revenue
product_revenue = df.groupby("Product")["Revenue"].sum()
print(product_revenue)

highest_revenue_product = product_revenue.idxmax()
highest_revenue_value = product_revenue.max()
print("\nHighest Revenue Product:",highest_revenue_product)
print("Revenue:",highest_revenue_value)

Product
Headphones     44000
Keyboard       21000
Laptop        165000
Monitor       125000
Mouse          28000
Phone         270000
Name: Revenue, dtype: int64

Highest Revenue Product: Phone
Revenue: 270000


In [43]:
#Category wise revenue
category_revenue = df.groupby("Category")["Revenue"].sum()
print(category_revenue)

Category
Accessories     93000
Electronics    560000
Name: Revenue, dtype: int64


In [44]:
#Highest rating products
high_rated_products = df[df["Rating"] >= 4.5]
print(high_rated_products[["Product","Rating"]])

       Product  Rating
0       Laptop     4.5
2   Headphones     4.7
4        Mouse     4.6
6       Laptop     4.8
8   Headphones     4.5
11       Mouse     4.7


In [45]:
average_rating = np.mean(df["Rating"].to_numpy())
print("\nAverage Product Rating:",round(average_rating, 2))


Average Product Rating: 4.42


In [46]:
#Find usually high revenue
mean_revenue = np.mean(revenue)
std_revenue = np.std(revenue)
threshold = mean_revenue + std_revenue
unusual_sales = df[df["Revenue"] > threshold]

print(unusual_sales[["Product","Quantity","Revenue"]])

  Product  Quantity  Revenue
0  Laptop         2   110000
1   Phone         5   150000
7   Phone         4   120000


In [47]:
# Rating contributes up to 100 points
# Quantity contributes additional points
# Creates persormance score
df["Performance_Score"] = (df["Rating"] * 20 + df["Quantity"] * 2)
print(df[["Product","Rating","Quantity","Performance_Score"]])

       Product  Rating  Quantity  Performance_Score
0       Laptop     4.5         2               94.0
1        Phone     4.2         5               94.0
2   Headphones     4.7        10              114.0
3     Keyboard     4.1         8               98.0
4        Mouse     4.6        15              122.0
5      Monitor     4.3         3               92.0
6       Laptop     4.8         1               98.0
7        Phone     4.0         4               88.0
8   Headphones     4.5        12              114.0
9      Monitor     4.4         2               92.0
10    Keyboard     4.2         6               96.0
11       Mouse     4.7        20              134.0


In [48]:
#Sort products by performance
ranked_products = df.sort_values("Performance_Score",ascending=False)
print(ranked_products[["Product","Performance_Score"]].head(5))

       Product  Performance_Score
11       Mouse              134.0
4        Mouse              122.0
2   Headphones              114.0
8   Headphones              114.0
3     Keyboard               98.0


In [49]:
#Numpy slicing
quantity_array = df["Quantity"].to_numpy()
print("All quantities:")
print(quantity_array)

print("\nFirst 5 quantities:")
print(quantity_array[:5])

print("\nLast 5 quantities:")
print(quantity_array[-5:])

All quantities:
[ 2  5 10  8 15  3  1  4 12  2  6 20]

First 5 quantities:
[ 2  5 10  8 15]

Last 5 quantities:
[ 4 12  2  6 20]


In [50]:
#Numpy Sorting
sorted_revenue = np.sort(revenue)
print("Revenue from lowest to highest:")
print(sorted_revenue)

Revenue from lowest to highest:
[  9000  12000  12000  16000  20000  24000  50000  55000  75000 110000
 120000 150000]


In [51]:
#Normalization demo
normalized_revenue = (revenue / np.max(revenue))
print(normalized_revenue)

[0.73333333 1.         0.13333333 0.08       0.08       0.5
 0.36666667 0.8        0.16       0.33333333 0.06       0.10666667]


In [52]:
#Final business report
print("FINAL BUSINESS REPORT")
print("\nTotal Revenue: ₹",np.sum(revenue))
print("Average Transaction Revenue: ₹",round(np.mean(revenue), 2))
print("Best Selling Product:",best_selling_product)
print("Highest Revenue Product:",highest_revenue_product)
print("Highest Revenue Transaction: ₹",np.max(revenue))
print("Average Rating:",round(average_rating, 2))
print("Number of Highly Rated Transactions:",len(high_rated_products))
print("Unusually High Revenue Transactions:",len(unusual_sales))

FINAL BUSINESS REPORT

Total Revenue: ₹ 653000
Average Transaction Revenue: ₹ 54416.67
Best Selling Product: Mouse
Highest Revenue Product: Phone
Highest Revenue Transaction: ₹ 150000
Average Rating: 4.42
Number of Highly Rated Transactions: 6
Unusually High Revenue Transactions: 3
